// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleInformation: typeof import('./.vitepress/theme/components/articleInformation.vue')['default']
    ChangeLog: typeof import('./.vitepress/theme/components/changeLog.vue')['default']
    Contributors: typeof import('./.vitepress/theme/components/contributors.vue')['default']
    CopyRight: typeof import('./.vitepress/theme/components/copyRight.vue')['default']
    ImgViewer: typeof import('./.vitepress/theme/components/imgViewer.vue')['default']
    OcticonClock16: typeof import('~icons/octicon/clock16')['default']
    OcticonGitCommit16: typeof import('~icons/octicon/git-commit16')['default']
    OcticonPerson16: typeof import('~icons/octicon/person16')['default']
    OcticonRocket16: typeof import('~icons/octicon/rocket16')['default']
    OcticonShareAndroid16: typeof import('~icons/octicon/share-android16')['default']
  }
}
